version: "3.7"

services:
  app:
    build: .
    restart: always
    networks:
      - traefik
      - default
    volumes:
      - ./media:/app/media
      - ./.env:/app/.env
      - /var/run/cups:/var/run/cups
    labels:
      - traefik.enable=true
      - traefik.http.routers.fredagscafeen.rule=Host(`fredagscafeen.dk`)
      - traefik.http.services.fredagscafeen.loadbalancer.server.port=8000
    depends_on:
      - db
      - media

  db:
    image: postgres:12
    volumes:
      - ./db_data:/var/lib/postgresql/data

  media:
    image: nginx:alpine
    volumes:
      - ./media:/usr/share/nginx/html
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.media-fredagscafeen.rule=Host(`media.fredagscafeen.dk`)
      - traefik.http.services.media-fredagscafeen.loadbalancer.server.port=80

networks:
  traefik:
    external: true
